const models = [
  {
    id: 1,
    name: "Sora",
    company: "OpenAI",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/120px-OpenAI_Logo.svg.png",
    logoFallback: "OA",
    description: "OpenAI's flagship text-to-video model capable of generating photorealistic videos up to 1 minute long from text prompts or images. Produces cinematic, high-quality footage with complex scene understanding.",
    tags: ["text-to-video", "image-to-video"],
    maxDuration: "Up to 60s",
    resolution: "Up to 1080p",
    pricing: "ChatGPT Plus / Pro",
    free: false,
    openSource: false,
    url: "https://sora.com",
    badges: ["🏆 Best Quality", "🎬 Cinematic"],
    released: "2024",
    highlight: true,
  },
  {
    id: 2,
    name: "Kling AI",
    company: "Kuaishou",
    logo: "",
    logoFallback: "KL",
    description: "Kling is Kuaishou's state-of-the-art video generation model offering high-fidelity motion, realistic physics simulation and both text-to-video and image-to-video generation up to 2 minutes.",
    tags: ["text-to-video", "image-to-video"],
    maxDuration: "Up to 2 min",
    resolution: "Up to 1080p",
    pricing: "Freemium",
    free: true,
    openSource: false,
    url: "https://klingai.com",
    badges: ["🔥 Trending", "⏱️ Long Videos"],
    released: "2024",
    highlight: true,
  },
  {
    id: 3,
    name: "Runway Gen-3 Alpha",
    company: "Runway",
    logo: "",
    logoFallback: "RW",
    description: "Runway's Gen-3 Alpha is a fast, high-fidelity text-to-video and image-to-video model optimized for creative and cinematic content. Supports motion brush, camera controls, and style presets.",
    tags: ["text-to-video", "image-to-video", "video-to-video"],
    maxDuration: "Up to 10s",
    resolution: "Up to 1280×768",
    pricing: "Subscription / Credits",
    free: true,
    openSource: false,
    url: "https://runwayml.com",
    badges: ["🎨 Creative Tools"],
    released: "2024",
    highlight: false,
  },
  {
    id: 4,
    name: "Luma Dream Machine",
    company: "Luma AI",
    logo: "",
    logoFallback: "LM",
    description: "Luma's Dream Machine generates high-quality, realistic videos from text and images. Known for smooth motion, accurate physics, and fast generation speeds with Ray2 model architecture.",
    tags: ["text-to-video", "image-to-video"],
    maxDuration: "Up to 9s",
    resolution: "Up to 1080p",
    pricing: "Freemium",
    free: true,
    openSource: false,
    url: "https://lumalabs.ai/dream-machine",
    badges: ["⚡ Fast Generation"],
    released: "2024",
    highlight: false,
  },
  {
    id: 5,
    name: "Hailuo AI (MiniMax)",
    company: "MiniMax",
    logo: "",
    logoFallback: "HL",
    description: "Hailuo Video by MiniMax produces photorealistic, high-motion videos with strong character consistency and subject motion. Supports text-to-video and image-to-video with excellent detail preservation.",
    tags: ["text-to-video", "image-to-video"],
    maxDuration: "Up to 6s",
    resolution: "Up to 1080p",
    pricing: "Freemium",
    free: true,
    openSource: false,
    url: "https://hailuoai.video",
    badges: ["👤 Character Motion"],
    released: "2024",
    highlight: false,
  },
  {
    id: 6,
    name: "Pika Labs",
    company: "Pika",
    logo: "",
    logoFallback: "PK",
    description: "Pika 2.0 offers expressive AI video generation with scene modification, text overlays, and a unique 'Pikaffects' feature for creative transformations. Great for social media and creative professionals.",
    tags: ["text-to-video", "image-to-video", "video-to-video"],
    maxDuration: "Up to 10s",
    resolution: "Up to 1080p",
    pricing: "Freemium",
    free: true,
    openSource: false,
    url: "https://pika.art",
    badges: ["✨ Creative FX"],
    released: "2024",
    highlight: false,
  },
  {
    id: 7,
    name: "Stable Video Diffusion",
    company: "Stability AI",
    logo: "",
    logoFallback: "SV",
    description: "Stability AI's open-source video diffusion model that animates still images into short video clips. Available for self-hosting and fine-tuning. SVD-XT supports 25-frame outputs.",
    tags: ["image-to-video", "open-source"],
    maxDuration: "~4s (25 frames)",
    resolution: "Up to 1024×576",
    pricing: "Free (self-hosted)",
    free: true,
    openSource: true,
    url: "https://stability.ai/stable-video",
    badges: ["🔓 Open Source", "🏠 Self-Hostable"],
    released: "2023",
    highlight: false,
  },
  {
    id: 8,
    name: "CogVideoX",
    company: "Zhipu AI / THUDM",
    logo: "",
    logoFallback: "CG",
    description: "CogVideoX is an open-source text-to-video model by Zhipu AI with strong semantic understanding. The 5B and 2B parameter models are freely available on HuggingFace for research and commercial use.",
    tags: ["text-to-video", "open-source"],
    maxDuration: "~6s",
    resolution: "Up to 720p",
    pricing: "Free (open-source)",
    free: true,
    openSource: true,
    url: "https://huggingface.co/THUDM/CogVideoX-5b",
    badges: ["🔓 Open Source", "🤗 HuggingFace"],
    released: "2024",
    highlight: false,
  },
  {
    id: 9,
    name: "Wan 2.1",
    company: "Alibaba",
    logo: "",
    logoFallback: "WN",
    description: "Wan 2.1 by Alibaba is a powerful open-source video generation model supporting text-to-video and image-to-video. The 14B model delivers high-quality output with multilingual prompt support.",
    tags: ["text-to-video", "image-to-video", "open-source"],
    maxDuration: "Up to ~10s",
    resolution: "Up to 1080p",
    pricing: "Free (open-source)",
    free: true,
    openSource: true,
    url: "https://github.com/Wan-Video/Wan2.1",
    badges: ["🔓 Open Source", "🌎 Multilingual"],
    released: "2025",
    highlight: true,
  },
  {
    id: 10,
    name: "HunyuanVideo",
    company: "Tencent",
    logo: "",
    logoFallback: "HY",
    description: "HunyuanVideo is Tencent's open-source text-to-video model with 13 billion parameters. It generates high-quality, consistent, motion-rich videos and rivals many closed-source alternatives.",
    tags: ["text-to-video", "open-source"],
    maxDuration: "Up to ~5s",
    resolution: "Up to 720p",
    pricing: "Free (open-source)",
    free: true,
    openSource: true,
    url: "https://github.com/Tencent/HunyuanVideo",
    badges: ["🔓 Open Source", "💪 13B Model"],
    released: "2024",
    highlight: false,
  },
  {
    id: 11,
    name: "Veo 2",
    company: "Google DeepMind",
    logo: "",
    logoFallback: "V2",
    description: "Veo 2 from Google DeepMind is one of the most advanced video generation models, producing high-fidelity 4K video content with deep cinematic control. Available via Google Vertex AI and VideoFX.",
    tags: ["text-to-video", "image-to-video"],
    maxDuration: "Up to 2 min",
    resolution: "Up to 4K",
    pricing: "Vertex AI / VideoFX",
    free: false,
    openSource: false,
    url: "https://deepmind.google/technologies/veo/",
    badges: ["🏆 4K Quality", "🎬 Cinematic"],
    released: "2024",
    highlight: true,
  },
  {
    id: 12,
    name: "Mochi 1",
    company: "Genmo",
    logo: "",
    logoFallback: "MO",
    description: "Mochi 1 by Genmo is an open-source video generation model with exceptional motion quality, fluid dynamics, and high fidelity. The 10B parameter Apache-licensed model is freely available.",
    tags: ["text-to-video", "open-source"],
    maxDuration: "~5.4s",
    resolution: "848×480",
    pricing: "Free (open-source)",
    free: true,
    openSource: true,
    url: "https://www.genmo.ai/play",
    badges: ["🔓 Open Source", "💫 Fluid Motion"],
    released: "2024",
    highlight: false,
  },
  {
    id: 13,
    name: "Pixverse",
    company: "Pixverse",
    logo: "",
    logoFallback: "PV",
    description: "PixVerse V4 offers fast video generation with strong character animation capabilities, template-based creation, and a generous free tier. Ideal for social content creators.",
    tags: ["text-to-video", "image-to-video"],
    maxDuration: "Up to 8s",
    resolution: "Up to 1080p",
    pricing: "Freemium",
    free: true,
    openSource: false,
    url: "https://pixverse.ai",
    badges: ["🆓 Generous Free Tier"],
    released: "2024",
    highlight: false,
  },
  {
    id: 14,
    name: "Invideo AI",
    company: "InVideo",
    logo: "",
    logoFallback: "IV",
    description: "InVideo AI creates full-length videos from text prompts, with stock footage integration, voiceovers, and auto-editing. More of a complete video production platform than a pure generative model.",
    tags: ["text-to-video"],
    maxDuration: "Full-length",
    resolution: "Up to 1080p",
    pricing: "Freemium",
    free: true,
    openSource: false,
    url: "https://invideo.io",
    badges: ["📹 Full Production", "🎙️ Voiceover"],
    released: "2023",
    highlight: false,
  },
  {
    id: 15,
    name: "Nova Reel",
    company: "Amazon AWS",
    logo: "",
    logoFallback: "NR",
    description: "Amazon Nova Reel is AWS's text-to-video and image-to-video generation model available on Amazon Bedrock. Supports up to 2-minute videos with camera motion control and consistent scene generation.",
    tags: ["text-to-video", "image-to-video"],
    maxDuration: "Up to 2 min",
    resolution: "1280×720",
    pricing: "AWS Bedrock (Pay-per-use)",
    free: false,
    openSource: false,
    url: "https://aws.amazon.com/bedrock/nova/",
    badges: ["☁️ Cloud API", "⏱️ Long Videos"],
    released: "2024",
    highlight: false,
  },
];
